-- MySQL Script generated by MySQL Workbench
-- 07/30/18 17:15:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mundoplay_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundoplay_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundoplay_v2` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `mundoplay_v2` ;

-- -----------------------------------------------------
-- Table `mundoplay_v2`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`generos` (
  `idgeneros` INT NOT NULL AUTO_INCREMENT,
  `nomegenero` VARCHAR(45) NULL,
  PRIMARY KEY (`idgeneros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`filmes` (
  `idfilmes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `titulo_original` VARCHAR(100) NULL,
  `elenco` TEXT NULL,
  `sinopse` TEXT NULL,
  `lancamento` DATE NULL,
  `duracao` INT NULL,
  `poster` VARCHAR(45) NULL,
  `trailer` VARCHAR(45) NULL,
  PRIMARY KEY (`idfilmes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`games` (
  `idgames` INT NOT NULL AUTO_INCREMENT,
  `tituloGame` VARCHAR(100) NULL,
  `diretor` VARCHAR(100) NULL,
  `sinopseGame` TEXT NULL,
  `imgGame` VARCHAR(45) NULL,
  `trailer` VARCHAR(45) NULL,
  PRIMARY KEY (`idgames`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`consoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`consoles` (
  `idconsoles` INT NOT NULL AUTO_INCREMENT,
  `nomeConsole` VARCHAR(45) NULL,
  PRIMARY KEY (`idconsoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`games_has_consoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`games_has_consoles` (
  `games_idgames` INT NOT NULL,
  `consoles_idconsoles` INT NOT NULL,
  PRIMARY KEY (`games_idgames`, `consoles_idconsoles`),
  INDEX `fk_games_has_consoles_consoles1_idx` (`consoles_idconsoles` ASC),
  INDEX `fk_games_has_consoles_games1_idx` (`games_idgames` ASC),
  CONSTRAINT `fk_games_has_consoles_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_consoles_consoles1`
    FOREIGN KEY (`consoles_idconsoles`)
    REFERENCES `mundoplay_v2`.`consoles` (`idconsoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`filmes_has_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`filmes_has_generos` (
  `filmes_idfilmes` INT NOT NULL,
  `generos_idgeneros` INT NOT NULL,
  PRIMARY KEY (`filmes_idfilmes`, `generos_idgeneros`),
  INDEX `fk_filmes_has_generos_generos1_idx` (`generos_idgeneros` ASC),
  INDEX `fk_filmes_has_generos_filmes1_idx` (`filmes_idfilmes` ASC),
  CONSTRAINT `fk_filmes_has_generos_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mundoplay_v2`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_has_generos_generos1`
    FOREIGN KEY (`generos_idgeneros`)
    REFERENCES `mundoplay_v2`.`generos` (`idgeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`games_has_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`games_has_generos` (
  `games_idgames` INT NOT NULL,
  `generos_idgeneros` INT NOT NULL,
  PRIMARY KEY (`games_idgames`, `generos_idgeneros`),
  INDEX `fk_games_has_generos_generos1_idx` (`generos_idgeneros` ASC),
  INDEX `fk_games_has_generos_games1_idx` (`games_idgames` ASC),
  CONSTRAINT `fk_games_has_generos_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_generos_generos1`
    FOREIGN KEY (`generos_idgeneros`)
    REFERENCES `mundoplay_v2`.`generos` (`idgeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`desenvolvedoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`desenvolvedoras` (
  `iddesenvolvedoras` INT NOT NULL AUTO_INCREMENT,
  `nomeDesenvolvedora` VARCHAR(100) NULL,
  PRIMARY KEY (`iddesenvolvedoras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`noticias` (
  `idnoticias` INT NOT NULL AUTO_INCREMENT,
  `tituloNoticia` VARCHAR(200) NULL,
  `subtitulo` VARCHAR(200) NULL,
  `texto` TEXT NULL,
  `dataPost` DATE NULL,
  `horaPost` TIME NULL,
  `img` VARCHAR(45) NULL,
  `destaque` CHAR(3) NULL DEFAULT 'off',
  `imgDestaque` VARCHAR(45) NULL,
  `relacionado` INT NULL,
  PRIMARY KEY (`idnoticias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `imgAutor` VARCHAR(45) NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`emissoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`emissoras` (
  `idemissoras` INT NOT NULL AUTO_INCREMENT,
  `nomeEmissora` VARCHAR(45) NULL,
  PRIMARY KEY (`idemissoras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`series` (
  `idseries` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `elenco` TEXT NULL,
  `sinopse` TEXT NULL,
  `canal` INT NULL,
  `temporadas` INT NULL,
  `poster` VARCHAR(45) NULL,
  `trailer` VARCHAR(45) NULL,
  PRIMARY KEY (`idseries`),
  INDEX `fk_emissora_idx` (`canal` ASC),
  CONSTRAINT `fk_emissora`
    FOREIGN KEY (`canal`)
    REFERENCES `mundoplay_v2`.`emissoras` (`idemissoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`series_has_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`series_has_generos` (
  `series_idseries` INT NOT NULL,
  `generos_idgeneros` INT NOT NULL,
  PRIMARY KEY (`series_idseries`, `generos_idgeneros`),
  INDEX `fk_series_has_generos_generos1_idx` (`generos_idgeneros` ASC),
  INDEX `fk_series_has_generos_series1_idx` (`series_idseries` ASC),
  CONSTRAINT `fk_series_has_generos_series1`
    FOREIGN KEY (`series_idseries`)
    REFERENCES `mundoplay_v2`.`series` (`idseries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_series_has_generos_generos1`
    FOREIGN KEY (`generos_idgeneros`)
    REFERENCES `mundoplay_v2`.`generos` (`idgeneros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`publicadoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`publicadoras` (
  `idpublicadora` INT NOT NULL AUTO_INCREMENT,
  `nomePublicadora` VARCHAR(100) NULL,
  PRIMARY KEY (`idpublicadora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `nomeTag` VARCHAR(45) NULL,
  PRIMARY KEY (`idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`tags_has_noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`tags_has_noticias` (
  `tags_idtags` INT NOT NULL,
  `noticias_idnoticias` INT NOT NULL,
  PRIMARY KEY (`tags_idtags`, `noticias_idnoticias`),
  INDEX `fk_tags_has_noticias_noticias1_idx` (`noticias_idnoticias` ASC),
  INDEX `fk_tags_has_noticias_tags1_idx` (`tags_idtags` ASC),
  CONSTRAINT `fk_tags_has_noticias_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `mundoplay_v2`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_noticias_noticias1`
    FOREIGN KEY (`noticias_idnoticias`)
    REFERENCES `mundoplay_v2`.`noticias` (`idnoticias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`tendencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`tendencias` (
  `idtendencias` INT NOT NULL AUTO_INCREMENT,
  `nomeTendencia` VARCHAR(100) NULL,
  `idtendencia_relac` INT NULL,
  `idtipoPost` INT NULL,
  `imgTendencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idtendencias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`midias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`midias` (
  `idmidias` INT NOT NULL AUTO_INCREMENT,
  `nomeMidia` VARCHAR(45) NULL,
  PRIMARY KEY (`idmidias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`midias_has_filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`midias_has_filmes` (
  `midias_idmidias` INT NOT NULL,
  `filmes_idfilmes` INT NOT NULL,
  PRIMARY KEY (`midias_idmidias`, `filmes_idfilmes`),
  INDEX `fk_midias_has_filmes_filmes1_idx` (`filmes_idfilmes` ASC),
  INDEX `fk_midias_has_filmes_midias1_idx` (`midias_idmidias` ASC),
  CONSTRAINT `fk_midias_has_filmes_midias1`
    FOREIGN KEY (`midias_idmidias`)
    REFERENCES `mundoplay_v2`.`midias` (`idmidias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_midias_has_filmes_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mundoplay_v2`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`midias_has_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`midias_has_series` (
  `midias_idmidias` INT NOT NULL,
  `series_idseries` INT NOT NULL,
  PRIMARY KEY (`midias_idmidias`, `series_idseries`),
  INDEX `fk_midias_has_series_series1_idx` (`series_idseries` ASC),
  INDEX `fk_midias_has_series_midias1_idx` (`midias_idmidias` ASC),
  CONSTRAINT `fk_midias_has_series_midias1`
    FOREIGN KEY (`midias_idmidias`)
    REFERENCES `mundoplay_v2`.`midias` (`idmidias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_midias_has_series_series1`
    FOREIGN KEY (`series_idseries`)
    REFERENCES `mundoplay_v2`.`series` (`idseries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`midias_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`midias_has_games` (
  `midias_idmidias` INT NOT NULL,
  `games_idgames` INT NOT NULL,
  PRIMARY KEY (`midias_idmidias`, `games_idgames`),
  INDEX `fk_midias_has_games_games1_idx` (`games_idgames` ASC),
  INDEX `fk_midias_has_games_midias1_idx` (`midias_idmidias` ASC),
  CONSTRAINT `fk_midias_has_games_midias1`
    FOREIGN KEY (`midias_idmidias`)
    REFERENCES `mundoplay_v2`.`midias` (`idmidias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_midias_has_games_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`desenvolvedoras_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`desenvolvedoras_has_games` (
  `desenvolvedoras_iddesenvolvedoras` INT NOT NULL,
  `games_idgames` INT NOT NULL,
  PRIMARY KEY (`desenvolvedoras_iddesenvolvedoras`, `games_idgames`),
  INDEX `fk_desenvolvedoras_has_games_games1_idx` (`games_idgames` ASC),
  INDEX `fk_desenvolvedoras_has_games_desenvolvedoras1_idx` (`desenvolvedoras_iddesenvolvedoras` ASC),
  CONSTRAINT `fk_desenvolvedoras_has_games_desenvolvedoras1`
    FOREIGN KEY (`desenvolvedoras_iddesenvolvedoras`)
    REFERENCES `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desenvolvedoras_has_games_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`publicadoras_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`publicadoras_has_games` (
  `publicadoras_idpublicadora` INT NOT NULL,
  `games_idgames` INT NOT NULL,
  PRIMARY KEY (`publicadoras_idpublicadora`, `games_idgames`),
  INDEX `fk_publicadoras_has_games_games1_idx` (`games_idgames` ASC),
  INDEX `fk_publicadoras_has_games_publicadoras1_idx` (`publicadoras_idpublicadora` ASC),
  CONSTRAINT `fk_publicadoras_has_games_publicadoras1`
    FOREIGN KEY (`publicadoras_idpublicadora`)
    REFERENCES `mundoplay_v2`.`publicadoras` (`idpublicadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicadoras_has_games_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`paises` (
  `idpaises` INT NOT NULL AUTO_INCREMENT,
  `nomePais` VARCHAR(45) NULL,
  PRIMARY KEY (`idpaises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`paises_has_filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`paises_has_filmes` (
  `paises_idpaises` INT NOT NULL,
  `filmes_idfilmes` INT NOT NULL,
  PRIMARY KEY (`paises_idpaises`, `filmes_idfilmes`),
  INDEX `fk_paises_has_filmes_filmes1_idx` (`filmes_idfilmes` ASC),
  INDEX `fk_paises_has_filmes_paises1_idx` (`paises_idpaises` ASC),
  CONSTRAINT `fk_paises_has_filmes_paises1`
    FOREIGN KEY (`paises_idpaises`)
    REFERENCES `mundoplay_v2`.`paises` (`idpaises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paises_has_filmes_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mundoplay_v2`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`paises_has_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`paises_has_series` (
  `paises_idpaises` INT NOT NULL,
  `series_idseries` INT NOT NULL,
  PRIMARY KEY (`paises_idpaises`, `series_idseries`),
  INDEX `fk_paises_has_series_series1_idx` (`series_idseries` ASC),
  INDEX `fk_paises_has_series_paises1_idx` (`paises_idpaises` ASC),
  CONSTRAINT `fk_paises_has_series_paises1`
    FOREIGN KEY (`paises_idpaises`)
    REFERENCES `mundoplay_v2`.`paises` (`idpaises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paises_has_series_series1`
    FOREIGN KEY (`series_idseries`)
    REFERENCES `mundoplay_v2`.`series` (`idseries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`paises_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`paises_has_games` (
  `paises_idpaises` INT NOT NULL,
  `games_idgames` INT NOT NULL,
  PRIMARY KEY (`paises_idpaises`, `games_idgames`),
  INDEX `fk_paises_has_games_games1_idx` (`games_idgames` ASC),
  INDEX `fk_paises_has_games_paises1_idx` (`paises_idpaises` ASC),
  CONSTRAINT `fk_paises_has_games_paises1`
    FOREIGN KEY (`paises_idpaises`)
    REFERENCES `mundoplay_v2`.`paises` (`idpaises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paises_has_games_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`midias_has_noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`midias_has_noticias` (
  `midias_idmidias` INT NOT NULL,
  `noticias_idnoticias` INT NOT NULL,
  PRIMARY KEY (`midias_idmidias`, `noticias_idnoticias`),
  INDEX `fk_midias_has_noticias_noticias1_idx` (`noticias_idnoticias` ASC),
  INDEX `fk_midias_has_noticias_midias1_idx` (`midias_idmidias` ASC),
  CONSTRAINT `fk_midias_has_noticias_midias1`
    FOREIGN KEY (`midias_idmidias`)
    REFERENCES `mundoplay_v2`.`midias` (`idmidias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_midias_has_noticias_noticias1`
    FOREIGN KEY (`noticias_idnoticias`)
    REFERENCES `mundoplay_v2`.`noticias` (`idnoticias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`noticias_has_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`noticias_has_login` (
  `noticias_idnoticias` INT NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`noticias_idnoticias`, `login_idlogin`),
  INDEX `fk_noticias_has_login_login1_idx` (`login_idlogin` ASC),
  INDEX `fk_noticias_has_login_noticias1_idx` (`noticias_idnoticias` ASC),
  CONSTRAINT `fk_noticias_has_login_noticias1`
    FOREIGN KEY (`noticias_idnoticias`)
    REFERENCES `mundoplay_v2`.`noticias` (`idnoticias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticias_has_login_login1`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `mundoplay_v2`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`diretores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`diretores` (
  `iddiretores` INT NOT NULL AUTO_INCREMENT,
  `nomeDiretor` VARCHAR(45) NULL,
  `sobrenomeDiretor` VARCHAR(45) NULL,
  PRIMARY KEY (`iddiretores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`filmes_has_diretores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`filmes_has_diretores` (
  `filmes_idfilmes` INT NOT NULL,
  `diretores_iddiretores` INT NOT NULL,
  PRIMARY KEY (`filmes_idfilmes`, `diretores_iddiretores`),
  INDEX `fk_filmes_has_diretores_diretores1_idx` (`diretores_iddiretores` ASC),
  INDEX `fk_filmes_has_diretores_filmes1_idx` (`filmes_idfilmes` ASC),
  CONSTRAINT `fk_filmes_has_diretores_filmes1`
    FOREIGN KEY (`filmes_idfilmes`)
    REFERENCES `mundoplay_v2`.`filmes` (`idfilmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_has_diretores_diretores1`
    FOREIGN KEY (`diretores_iddiretores`)
    REFERENCES `mundoplay_v2`.`diretores` (`iddiretores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`diretores_has_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`diretores_has_series` (
  `diretores_iddiretores` INT NOT NULL,
  `series_idseries` INT NOT NULL,
  PRIMARY KEY (`diretores_iddiretores`, `series_idseries`),
  INDEX `fk_diretores_has_series_series1_idx` (`series_idseries` ASC),
  INDEX `fk_diretores_has_series_diretores1_idx` (`diretores_iddiretores` ASC),
  CONSTRAINT `fk_diretores_has_series_diretores1`
    FOREIGN KEY (`diretores_iddiretores`)
    REFERENCES `mundoplay_v2`.`diretores` (`iddiretores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diretores_has_series_series1`
    FOREIGN KEY (`series_idseries`)
    REFERENCES `mundoplay_v2`.`series` (`idseries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundoplay_v2`.`games_has_diretores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundoplay_v2`.`games_has_diretores` (
  `games_idgames` INT NOT NULL,
  `diretores_iddiretores` INT NOT NULL,
  PRIMARY KEY (`games_idgames`, `diretores_iddiretores`),
  INDEX `fk_games_has_diretores_diretores1_idx` (`diretores_iddiretores` ASC),
  INDEX `fk_games_has_diretores_games1_idx` (`games_idgames` ASC),
  CONSTRAINT `fk_games_has_diretores_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `mundoplay_v2`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_diretores_diretores1`
    FOREIGN KEY (`diretores_iddiretores`)
    REFERENCES `mundoplay_v2`.`diretores` (`iddiretores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`generos`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Terror');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Ação');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Drama');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Suspense');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Aventura');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Nacional');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Comédia');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Fantasia');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Sci-Fi');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Western');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Não especificado');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'FPS');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Estratégia');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'RPG');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Simulador');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Esporte');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Sandbox');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Plataforma');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, '2D');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Animação');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Policial');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Battle Royal');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'TPS');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Casual');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Luta');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Interativo');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Corrida');
INSERT INTO `mundoplay_v2`.`generos` (`idgeneros`, `nomegenero`) VALUES (NULL, 'Documentário');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`consoles`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'PlayStation 4');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'Xbox One');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'Nintendo Switch');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'PlayStation 3');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'Xbox 360');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'Nintendo WiiU');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'PS Vita');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'Nintendo 3DS');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'PC');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'iOS');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'Windows');
INSERT INTO `mundoplay_v2`.`consoles` (`idconsoles`, `nomeConsole`) VALUES (NULL, 'macOS');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`desenvolvedoras`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'SCE Santa Monica');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Ubisoft Montreal');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Undead Labs');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Retro Studios');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'QLOC');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Nintendo Entertainment Planning & Development');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'EA Canada');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Epic Games');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Konami Digital Entertainment');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Arc System Works');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Quantic Dream');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Backbone Entertainment');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Playground Games');
INSERT INTO `mundoplay_v2`.`desenvolvedoras` (`iddesenvolvedoras`, `nomeDesenvolvedora`) VALUES (NULL, 'Codemasters');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`login`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`login` (`idlogin`, `nome`, `email`, `usuario`, `senha`, `imgAutor`) VALUES (NULL, 'Thiago Silva', 'stornwild@yahoo.com.br', 'thiago', '$2y$10$LZGGLN.ZoKKVOOdmEYN4V.DrAiJGUVN7.gDKYNDc3HAgVATyKwIFy', 'thiago_silva.jpg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`tags`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'E3 2018');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Reportagem');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'PlayStation');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Microsoft');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Nintendo');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Oscar');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'PS4');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Xbox One');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Marvel');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Vingadores');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'TV');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Hulu');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Bilheteria');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Westworld');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Spoiler');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'HBO');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Steam');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Switch');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Remaster');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'GoT');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'EA');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'FX');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Dell');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Hardware');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'CBS');
INSERT INTO `mundoplay_v2`.`tags` (`idtags`, `nomeTag`) VALUES (NULL, 'Jurassic World');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`tendencias`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`tendencias` (`idtendencias`, `nomeTendencia`, `idtendencia_relac`, `idtipoPost`, `imgTendencia`) VALUES (NULL, 'Westworld', 3, 3, 'trend_westworld.jpg');
INSERT INTO `mundoplay_v2`.`tendencias` (`idtendencias`, `nomeTendencia`, `idtendencia_relac`, `idtipoPost`, `imgTendencia`) VALUES (NULL, 'Vingadores 3', 1, 1, 'trend_vingadores3.jpg');
INSERT INTO `mundoplay_v2`.`tendencias` (`idtendencias`, `nomeTendencia`, `idtendencia_relac`, `idtipoPost`, `imgTendencia`) VALUES (NULL, 'The Handmaids Tale', 2, 3, 'trend_handmaids.jpg');
INSERT INTO `mundoplay_v2`.`tendencias` (`idtendencias`, `nomeTendencia`, `idtendencia_relac`, `idtipoPost`, `imgTendencia`) VALUES (NULL, 'E3', 1, 3, 'trend_e32018.jpg');
INSERT INTO `mundoplay_v2`.`tendencias` (`idtendencias`, `nomeTendencia`, `idtendencia_relac`, `idtipoPost`, `imgTendencia`) VALUES (NULL, 'Jurassic World', 3, 1, 'trend_jurassicworld.jpg');
INSERT INTO `mundoplay_v2`.`tendencias` (`idtendencias`, `nomeTendencia`, `idtendencia_relac`, `idtipoPost`, `imgTendencia`) VALUES (NULL, 'Comic-Con 2018', 1, 1, 'comiccon2018.jpg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`midias`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`midias` (`idmidias`, `nomeMidia`) VALUES (NULL, 'Cinema');
INSERT INTO `mundoplay_v2`.`midias` (`idmidias`, `nomeMidia`) VALUES (NULL, 'Séries');
INSERT INTO `mundoplay_v2`.`midias` (`idmidias`, `nomeMidia`) VALUES (NULL, 'Games');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`paises`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`paises` (`idpaises`, `nomePais`) VALUES (NULL, 'Estados Unidos');
INSERT INTO `mundoplay_v2`.`paises` (`idpaises`, `nomePais`) VALUES (NULL, 'França');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mundoplay_v2`.`diretores`
-- -----------------------------------------------------
START TRANSACTION;
USE `mundoplay_v2`;
INSERT INTO `mundoplay_v2`.`diretores` (`iddiretores`, `nomeDiretor`, `sobrenomeDiretor`) VALUES (NULL, 'Diretor 1', 'Sobrenome 1');
INSERT INTO `mundoplay_v2`.`diretores` (`iddiretores`, `nomeDiretor`, `sobrenomeDiretor`) VALUES (NULL, 'Diretor 2', 'Sobrenome 2');

COMMIT;

